### ISSUE TITLE
Training Weapons causes Lag Spikes

### ISSUE THREAD

**Issue by JukeDragh** [jptrrs/HumanResources#67]
Hey again, I found another thing to look into. 
I set up a Target Stand to start teaching my colonists. Shortly after I set up a bill, lag spikes of almost 10 seconds started happening. I used Performance Analyzer to get this:

![Human Resources Training Lag Spike](https://user-images.githubusercontent.com/26523083/88455400-9adfba80-ce3a-11ea-94ee-e6b0975a240c.png)

Pretty much confirms that the Target Stand training bill is responsible. 
The Bill is set to:
- Any Worker
- All weapons

I have a feeling the spikes are a reflection of the number of ranged weapons in my heavily modded game. I am gonna do a bit of testing to see if the issue is deeper than that.

**Comment by JukeDragh** [comment]
Okay, I did a little bit of testing and have a few more insights.
I actually got a perceptible amount of lag (300 millisecond) just by selecting a single weapon: A Greatbow
I have one on the map and none of my colonists have the greatbow tech nor any clue how to wield it.
I tried the same with the Pump Shotgun which I did have tech for and the spike was miniscule.
Next with the Recurve Bow that is under the same circumstances as the Greatbow. I get the lag spike.

The two bows are the only things that fall under those conditions so I did Allow All minus the bows on the bill. No lag.
Here is a list of a couple different tests I did around these conditions:

- No Bows but All Others: 24ms
- Bows and All Others: 4376ms
- 1 Bow and All Others: 4333ms
- Only Bows: 432ms
- 1 Bow: 290ms
- Every Weapon minus 1 Rimarsenal Category: 3933ms
- Every Weapon minus All Rimarsenal Categories: 2508ms
- Only Rimarsenal Categories: 24ms

It looks as though its actually both things contributing to the spike. There is something about a weapon that you don't have the tech for being on the map that causes it to run through every single weapon.

**Comment by JukeDragh** [comment]
https://gist.github.com/HugsLibRecordKeeper/513b31e30800b3fc891f678d32a952ea
The Log btw. There was pretty much nothing of note (afaik) besides a ScribeObjectValue trying to use null and the mod scolding me for letting a nonviolent pawn Train. Nothing appears in the logs whenever the spikes occur.

**Comment by jptrrs** [comment]
Thanks for investigating it! I'll take a look when I can.

**Comment by ELLIOTTCABLE** [comment]
I'm also seeing a similar lag-spike, but it *looks* like it's occasionally associated with an error on my end:

```
Exception in RimWorld.ThinkNode_ConditionalColonist TryIssueJobPackage: System.NullReferenceException: Object reference not set to an instance of an object
  at HumanResources.HarmonyPatches.CheckKnownWeapons (Verse.Pawn pawn, Verse.Thing thing) [0x00001] in <534dd973ab3740f18ef61ee9a76e58fa>:0 
  at HumanResources.SimpleSidearms_Patches.equipSpecificWeapon_Prefix (Verse.Pawn pawn, Verse.ThingWithComps weapon) [0x00033] in <534dd973ab3740f18ef61ee9a76e58fa>:0 
  at (wrapper dynamic-method) SimpleSidearms.utilities.WeaponAssingment.SimpleSidearms.utilities.WeaponAssingment.equipSpecificWeapon_Patch1(Verse.Pawn,Verse.ThingWithComps,bool,bool)
  at SimpleSidearms.utilities.WeaponAssingment.equipBestWeaponFromInventoryByPreference (Verse.Pawn pawn, SimpleSidearms.Globals+DroppingModeEnum drop, System.Nullable`1[T] modeOverride, Verse.Pawn target) [0x001c1] in <dc8a5df38a4349aeaabc68a715d779e0>:0 
  at SimpleSidearms.rimworld.JobGiver_QuicklySwitchWeapons.TryGiveJobStatic (Verse.Pawn pawn, System.Boolean inCombat) [0x0005a] in <dc8a5df38a4349aeaabc68a715d779e0>:0 
  at SimpleSidearms.rimworld.JobGiver_QuicklySwitchWeapons.TryGiveJob (Verse.Pawn pawn) [0x00001] in <dc8a5df38a4349aeaabc68a715d779e0>:0 
  at Verse.AI.ThinkNode_JobGiver.TryIssueJobPackage (Verse.Pawn pawn, Verse.AI.JobIssueParams jobParams) [0x00000] in <0ee2c524c4be441e9b7f8bfcb20aca6f>:0 
  at Verse.AI.ThinkNode_Priority.TryIssueJobPackage (Verse.Pawn pawn, Verse.AI.JobIssueParams jobParams) [0x00022] in <0ee2c524c4be441e9b7f8bfcb20aca6f>:0 
Verse.Log:Error(String, Boolean)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Conditional:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.DetermineNextJob_Patch4(Pawn_JobTracker, ThinkTreeDef&)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.EndCurrentJob_Patch1(Pawn_JobTracker, JobCondition, Boolean, Boolean)
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Verse.Pawn.Tick_Patch2(Pawn)
Verse.TickList:Verse.TickList.Tick_Patch2(TickList)
Verse.TickManager:Verse.TickManager.DoSingleTick_Patch0(TickManager)
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Verse.Root_Play.Update_Patch1(Root_Play)
```

**Comment by jptrrs** [comment]
Hi there. There's a good chance this has been solved with one of the many updates since. But I wanted to throw some light here to help anyone facing lag with the training weapon recipes. In order to see if the job should be triggered, the work giver needs to search the map for every weapon selected on the bill and compare it with the pawn's knowledge. If the weapons list is too large, this can be a demanding task. If you're experiencing this regularly, it helps to keep only the desired weapon selected on the bill.

**Comment by Itaros** [comment]
I would like to let you know: issue is not solved. Current(at the moment of comment) version from Steam still lags like hell when attempting to train weapons.

Interestingly enough: 
- limiting weapon selection doesn't reduce lag
- lag grows exponentialy to amount of training furniture with active training bills

I believe this issue should be promoted to critical because it is quite impactful.

**Comment by jptrrs** [comment]
Itaros: You're most probably facing a mod conflict, but I'm going to need a lot more information to be able to do anything about it. Please follow this instructions: https://steamcommunity.com/workshop/filedetails/discussion/2119687603/2295094308095765898/

**Comment by Itaros** [comment]
No, it is not. It is method which scans suitable weapons which is slow. Seen the code. Is it: https://github.com/jptrrs/HumanResources/blob/8a19baf5ce501c2078916c1a167ae5438279c347/Source/Work/WorkGiver_LearnWeapon.cs#L135-L151 ?. Behavior is quite as written: it is slow by design. Reducing mod count with weapons reduces lag. 
I believe it may be solved by introducing caching of available weapons with slow scanning per bill. That will make it not immediate, but at least it will not scale up in lag.
![slow_by_design](https://user-images.githubusercontent.com/6721826/118547881-4f4c2380-b762-11eb-90fe-541fb86bc8c6.PNG)

Addendum: I wonder how LINQ Remove etc methods are performant. Wouldn't be reusable mask faster in C#?
Addendum 2: I have no clue how to mod Rimworld, but going to try to setup environment and try to at least optimize this path without changing how it works. No promises, but in case of success will drop a PR.

**Comment by jptrrs** [comment]
It seems to come down to what you'd consider "lag". On my setup, running almost 300 mods, I get a much worse average than that with just one active recipe. Yet, no perceptible performance loss. I just tested up to 30 target stands with experiment weapons bills, all weapons selected, and that average almost reached 1.0 ms. But no FPS drop whatsoever. 
Did you noticed anything while playing? Or was it just comparing things with the analyzer?
Anyway, If you're able to devise any improvement that doesn't break something else, I'd promptly incorporate it!
Best luck!

**Comment by jptrrs** [comment]
The pathway for weapon validation has been rewritten, making this obsolete.
