### ISSUE TITLE
(Bug) recreation super training

### ISSUE THREAD

**Issue by kaczorski** [jptrrs/HumanResources#90]
Built a training dummy and didn't set up any bills (it was meant just for recreation). When colonist with a short bow started using it, his shooting started levelling at a crazy pace.  Log was totally blank and recreation was unaffected :( 

On a side note, no ammunition was lost (I'm using Yayo's combat) but it probably makes sense since they can use ranged weapons in melee.

**Comment by jptrrs** [comment]
Can you try setting up a "practice with weapon" bill and check if the leveling with it is any slower?

**Comment by kaczorski** [comment]
Sure thing. 

Nope, its still crazy fast. Pawn without a passion is training melee well... ultra quick. No human being should be able to level so fast :P


Plus I'm getting this error when Howe does practice shooting at the archery target:

Exception in ToString(): System.NullReferenceException: Object reference not set to an instance of an object
  at Verse.AI.Job.ToString () [0x00000] in <d72310b4d8f64d25aee502792b58549f>:0 
  at Verse.Gen.ToStringSafe[T] (T obj) [0x0000f] in <d72310b4d8f64d25aee502792b58549f>:0 
Verse.Log:Error(String, Boolean)
Verse.Log:ErrorOnce(String, Int32, Boolean)
Verse.Gen:ToStringSafe(Job)
Verse.AI.JobUtility:AppendVarsInfoToDebugMessage(Pawn, String&, JobDriver)
Verse.AI.JobUtility:TryStartErrorRecoverJob(Pawn, String, Exception, JobDriver)
Verse.AI.JobDriver:Verse.AI.JobDriver.DriverTick_Patch1(JobDriver)
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Verse.Pawn.Tick_Patch4(Pawn)
Verse.TickList:Verse.TickList.Tick_Patch2(TickList)
Verse.TickManager:Verse.TickManager.DoSingleTick_Patch4(TickManager)
Verse.TickManager:TickManagerUpdate()
Verse.Game:Verse.Game.UpdatePlay_Patch3(Game)
Verse.Root_Play:Verse.Root_Play.Update_Patch0(Root_Play)

Exception in JobDriver tick for pawn Howe driver=JobDriver_LearnWeapon (toilIndex=3) driver.job=(error)
System.NullReferenceException: Object reference not set to an instance of an object
  at HumanResources.JobDriver_LearnWeapon+<>c__DisplayClass16_0.<Train>b__1 () [0x0015a] in <bded54154f444d37b682583d86e7f700>:0 
  at (wrapper dynamic-method) Verse.AI.JobDriver.Verse.AI.JobDriver.DriverTick_Patch1(Verse.AI.JobDriver)
Verse.Log:Error(String, Boolean)
Verse.AI.JobUtility:TryStartErrorRecoverJob(Pawn, String, Exception, JobDriver)
Verse.AI.JobDriver:Verse.AI.JobDriver.DriverTick_Patch1(JobDriver)
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Verse.Pawn.Tick_Patch4(Pawn)
Verse.TickList:Verse.TickList.Tick_Patch2(TickList)
Verse.TickManager:Verse.TickManager.DoSingleTick_Patch4(TickManager)
Verse.TickManager:TickManagerUpdate()
Verse.Game:Verse.Game.UpdatePlay_Patch3(Game)
Verse.Root_Play:Verse.Root_Play.Update_Patch0(Root_Play)

**Comment by Thieffi** [comment]
I didn't test it much, but I did notice this issue too; even if a pawn does not have a passion on a shooting/melee, they will gain experience on the skill really fast. The skill gain is comparable to a pawn with burning passion (+ trait with learning bonus). It seems to be somewhat similar whether the pawn was competing the bill, or using the dummy or the target for entertainment.

**Comment by jptrrs** [comment]
Ok, thanks for testing and thanks for the info, @Thieffi. 
If there are no differences between both training modes, that's probably not due to this week's updates. To be certain, you guys can try using the last version before the introduction of the Joy activities: https://github.com/jptrrs/HumanResources/releases/tag/v0.18
An unexpected thing is the guy with a shortbow using the training dummy. But I reviewed the code and updated the mod, this shouldn't happen anymore.
About the leveling speed, though, I have no clue. There might me some other mods interfering. Did you try loading just Core + HugsLib + ResearchTree/Pal + HumanResources? If you guys can identify the conflict, please send me your whole Ctrl+F12 error log.

**Comment by jptrrs** [comment]
OK, I can confirm this error happening, even though I could not pinpoint the cause yet. To prevent it, I've suspended XP gain on the recreation activities. The mod was updated.

**Comment by Thieffi** [comment]
This still seems to happen sometimes, but it has seemed too random to properly test, especially as it doesn't generate a log entry. However, after playing a bunch I have a suspicion that it might a compatibility issue with Simple Sidearms (possible cause is the 'Tool use autoswitch' setting, where pawns auto-equip tools from their inventory if they provide bonuses to the task they are doing).

**Comment by jptrrs** [comment]
@Thieffi: if your pawns are still getting any xp gain when practicing weapons as a recreation activity, then your files are not up-to-date. Or are you referring to pawns doing regular practice shooting/melee bills?

**Comment by Thieffi** [comment]
They are using the target and the dummy for recreation. My files are up to date, after the update where xp from recreation was removed, they no longer get xp in most cases, but occasionally this super fast training occurs; sometimes it happens while using the ranged target and other times the pawns might wield a ranged weapon while using the melee dummy for recreation. The latter seems to always be super training. I have just one bill on each to learn to use a weapon, which I enable whenever I want a pawn to learn to use a new weapon.

**Comment by jptrrs** [comment]
Ok, I found out what was causing the recreation activity not to filter ranged weapons out. Its fixed now. 
Let's hope that eliminates the last opportunity for the "super-training" issue to occur, even though I still wasn't able to pinpoint what actually causes it. Please, keep an eye on this when pawns are training, just in case.
Thanks!

**Comment by Thieffi** [comment]
Unfortunately this still occurs as evidenced by my cook's shooting skill from one training session: https://i.imgur.com/9XvPBri.png (using a ranged weapon on the target stand)

There seems to be something even weirder going on as another pawn was training on the target stand gaining negative skill xp: https://i.imgur.com/cfQv7B7.png 

Maybe there's an errant multiplier somewhere which is somehow applying to the pawn's xp change, be it either increase from training or decrease from skill decay? The effect is greatly increased on pawns with passion for shooting.

Pawns did stop using ranged weapons on the melee dummy, so that seems to be fixed. Also it seems to be only the shooting skill that's boosted, the melee skill increases at a normal pace.

**Comment by jptrrs** [comment]
Ok, you know the drill: I need your log and I need to know the setup: what bill they're doing and how it is configured.

**Comment by Thieffi** [comment]
The log itself won't tell anything because I had another mod that generated so much deep-save related log spam that the game stopped logging (Tracked that to Desynchronized: Tales and News (Continued)). I disabled that but removing it requires me to start a new game to research this issue further. I did however spend four hours in dev mode in my 10 pawn colony staring at the debug log and the general activity around the target stand and the melee dummy:

The activity they are performing is 'PlayAtTarget' both when they are super training and when they aren't gaining xp from the activity; this seems almost random. One day a pawn might not get any xp, and the next day a training/joy session gives him 50k. It also doesn't depend on a pawn's weapon (tried one pawn with both a gun and a bow, on both he on different sessions, super trained or got just joy), happens regardless of passion (the passion multiplier seems to calculate somewhat correctly, not sure about the multiplier from having trained too much in one day). Some pawns seem to get super training more often than others, but I haven't been able to figure out the correlation. I have a bill active on the target for learning to shoot the greatbow, but as everyone already learned that, they aren't using it for that and I only have it there to get rid of the 'Empty workbench' alert.

I am almost sure this is a compatibility issue with another mod, just can't tell which one. I tested with just HumanResources and created a colony with 20 pawns stocked with survival meals, scheduled everyone for entertainment, gave them bows and placed a row of targets, and let the game just run for a few days; no super training. Next I added a few mods from my previous list of mods, which I felt had some impact on how the pawn logic works with skills, training or weapons in general, and did the same as above; no problem. The list:

- Harmony
- Core
- Royalty
- HugsLib
- Achtung!
- Common Sense
- Misc. Training
- Numbers (patched) 1.2
- PawnTargetFix
- Psychology (unofficial 1.1/1.2)
- ResearchPal
- RimHUD
- RunAndGun
- Simple sidearms
- What's That Mod
- [JPT] Human Resources

There was a red error when a pawn went to train on a melee dummy, but turns out that has nothing to do with this mod, but was caused by Simple sidearms; happened also when a pawn got in a fight, caused by switching from a primary ranged weapon to a melee side arm. Same thing a ranged pawn does when going to train on the melee dummy.

Now I need at least a few days break from RimWorld so won't be doing further testing at least this week.

**Comment by jptrrs** [comment]
Wow, thanks for this investigation! I still need the log to verify a couple of things, but it does smell like some other mod is interfering. I have a hunch, though....
You say 'PlayAtTarget' is active when they get the super-training... our recreation activity should NOT trigger xp gain of any kind anymore! I recently ran into an issue with Steam not updating a mod properly. If this happened to you and a particular xml file did not update, this could trigger the bug. So I'm going to ask for you to verify it. Its easy!
The file is called the "Jobs.xml", you will find it at the mod's Defs folder (usually C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2119687603\Defs). You can open it with notepad and paste it here so I can check or look yourself at line 44: it should start with "`<!--`", right before "`<joySkill>Melee</joySkill>`". If it doesn't, then the update process is messed up and it would explain a lot! Otherwise, if the file is right, then the XP gain is probably not being handled by vanilla code but something else. Either way we get some answers...

**Comment by Thieffi** [comment]
Here's the log: https://gist.github.com/HugsLibRecordKeeper/ebf519361c295a28a4d60d461aec746a

I checked the Jobs.xml and joySkill is commented out on both the dummy and the target, so the issue lies elsewhere.

**Comment by jptrrs** [comment]
Thanks for the log, Thieffi. 
Please, everyone, check if the issue is fixed on the latest update, version 0.26. I've re-worked the bit where the training process simulates a shot so it doesn't actually trigger a shot.

**Comment by Thieffi** [comment]
I haven't noticed this issue anymore, but I've also done some heavy editing on my modset; shuffled things around, replaced some mods removed some, so can't say for sure if it was fixed by the update or there was some unknown compatibility issue.

**Comment by jptrrs** [comment]
There's a resonable chance that last change killed it, but since this has been an unusually persistent bug and we couldn't pinpoint the root of the problem I'll leave this open for now.

**Comment by jptrrs** [comment]
Three months later, no complaints: we can call this a win. ;-)
